<?php

namespace Database\Seeders;

use App\Models\Admin;
use App\Models\Rating;
use App\Models\Users;
use App\Models\Wisata;
use Illuminate\Database\Seeder;
use Illuminate\Foundation\Auth\User;
use Illuminate\Validation\Rules\Unique;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        // $user = [
        //     [
        //     'id_admin'=>'001',
        //     'username'=>'admin123',
        //     'password'=> 'admin123',
        //     'nama_admin'=>'admin',
        //     'jk'=>'Laki-laki',
        //     'no_hp'=>'082198761234'
        //     ]
        // ];
        // foreach($user as $key => $value){
        //     Admin::create($value);
        // }


        $users = [
            ['Suenti Een', 'gmail.com', 'password', 'Suenti Een', 'Perempuan', 'no_hp', 'cirebon'],
['Ang Yon', 'gmail.com','password','Ang Yon', 'Laki-Laki', 'no_hp', 'cirebon'],
['Moelyadi Baleela', 'gmail.com', 'password', 'Moelyadi Baleela', 'Laki-Laki', 'no_hp', 'cirebon'],
['Khosiah Osi', 'gmail.com', 'password', 'Khosiah Osi', 'Perempuan', 'no_hp', 'cirebon'],
['Nuraeni Indah Sari', 'gmail.com', 'password', 'Nuraeni Indah Sari', 'Perempuan', 'no_hp', 'cirebon'],
['Burhanudin Bram', 'gmail.com', 'password', 'Burhanudin Bram', 'Laki-Laki', 'no_hp', 'cirebon'],
['Prana Kunji', 'gmail.com', 'password', 'Prana Kunji', 'Laki-Laki', 'no_hp', 'cirebon'],
['Bilqis Nabila', 'gmail.com', 'password', 'Bilqis Nabila', 'Perempuan', 'no_hp', 'cirebon'],
['Jefry Anthony', 'gmail.com', 'password', 'Jefry Anthony', 'Laki-Laki', 'no_hp', 'cirebon'],
['AF Ashari', 'gmail.com', 'password', 'AF Ashari', 'Laki-Laki', 'no_hp', 'cirebon'],
['Za Irawan', 'gmail.com', 'password', 'Za Irawan', 'Laki-Laki', 'no_hp', 'cirebon'],
['RBS 09', 'gmail.com', 'password', 'RBS 09', 'Laki-Laki', 'no_hp', 'cirebon'],
['Kunto Dwi', 'gmail.com', 'password', 'Kunto Dwi', 'Laki-Laki', 'no_hp', 'cirebon'],
['Hesty Kartikasari', 'gmail.com', 'password', 'Hesty Kartikasari', 'Perempuan', 'no_hp', 'cirebon'],
['Fatimah Pamungkas', 'gmail.com', 'password', 'Fatimah Pamungkas', 'Perempuan', 'no_hp', 'cirebon'],
['Abdurakhman Wahid', 'gmail.com', 'password', 'Abdurakhman Wahid', 'Laki-Laki', 'no_hp', 'cirebon'],
['Hardi Tabuti', 'gmail.com', 'password', 'Hardi Tabuti', 'Laki-Laki', 'no_hp', 'cirebon'],
['Mohammad Ridwan', 'gmail.com', 'password', 'Mohammad Ridwan', 'Laki-Laki', 'no_hp', 'cirebon'],
['Sys', 'gmail.com', 'password', 'Sys', 'Laki-Laki', 'no_hp', 'cirebon'],
['Yuni Suman', 'gmail.com', 'password', 'Yuni Suman', 'Perempuan', 'no_hp', 'cirebon'],
['Kang Umun', 'gmail.com', 'password', 'Kang Umun', 'Laki-Laki', 'no_hp', 'cirebon'],
['Ali Umar', 'gmail.com', 'password', 'Ali Umar', 'Laki-Laki', 'no_hp', 'cirebon'],
['Moms Aryan', 'gmail.com', 'password', 'Moms Aryan', 'Perempuan', 'no_hp', 'cirebon'],
['Monica Candra Dewi', 'gmail.com', 'password', 'Monica Candra Dewi', 'Perempuan', 'no_hp', 'cirebon'],
['Hermawan Fawwaz', 'gmail.com', 'password', 'Hermawan Fawwaz', 'Laki-Laki', 'no_hp', 'cirebon'],
['Nur Soleh', 'gmail.com', 'password', 'Nur Soleh', 'Laki-Laki', 'no_hp', 'cirebon'],
['Tani Wijaya', 'gmail.com', 'password', 'Tani Wijaya', 'Laki-Laki', 'no_hp', 'cirebon'],
['Aidil Fitrah', 'gmail.com', 'password', 'Aidil Fitrah', 'Laki-Laki', 'no_hp', 'cirebon'],
['Bang Nizar', 'gmail.com', 'password', 'Bang Nizar', 'Laki-Laki', 'no_hp', 'cirebon'],
['Jaojatun Marup', 'gmail.com', 'password', 'Jaojatun Marup', 'Perempuan', 'no_hp', 'cirebon'],
['Hanifah', 'gmail.com', 'password', 'Hanifah', 'Perempuan', 'no_hp', 'cirebon'],
['Mardi Yanto', 'gmail.com', 'password', 'Mardi Yanto', 'Laki-Laki', 'no_hp', 'cirebon'],
['Ahmad Fadlu', 'gmail.com', 'password', 'Ahmad Fadlu', 'Laki-Laki', 'no_hp', 'cirebon'],
['Tunass Rieziek', 'gmail.com', 'password', 'Tunass Rieziek', 'Laki-Laki', 'no_hp', 'cirebon'],
['Abank', 'gmail.com', 'password', 'Abank', 'Laki-Laki', 'no_hp', 'cirebon'],
['Yadi Suripto', 'gmail.com', 'password', 'Yadi Suripto', 'Laki-Laki', 'no_hp', 'cirebon'],
['Nani Amani', 'gmail.com', 'password', 'Nani Amani', 'Perempuan', 'no_hp', 'cirebon'],
['Alexa Crb', 'gmail.com', 'password', 'Alexa Crb', 'Perempuan', 'no_hp', 'cirebon'],
['Sutara', 'gmail.com', 'password', 'Sutara', 'Laki-Laki', 'no_hp', 'cirebon'],
['Wahid Paruza', 'gmail.com', 'password', 'Wahid Paruza', 'Laki-Laki', 'no_hp', 'cirebon'],
['Idemen', 'gmail.com', 'password', 'Idemen', 'Laki-Laki', 'no_hp', 'cirebon'],
['Risna Lijaman', 'gmail.com', 'password', 'Risna Lijaman', 'Perempuan', 'no_hp', 'cirebon'],
['Waviq Azizah', 'gmail.com', 'password', 'Waviq Azizah', 'Laki-Laki', 'no_hp', 'cirebon'],
['Dena Febrian', 'gmail.com', 'password', 'Dena Febrian', 'Perempuan', 'no_hp', 'cirebon'],
['Turadi', 'gmail.com', 'password', 'Turadi', 'Laki-Laki', 'no_hp', 'cirebon'],
['Farhan Septian', 'gmail.com', 'password', 'Farhan Septian', 'Laki-Laki', 'no_hp', 'cirebon'],
['Fajariah Tri Lestari', 'gmail.com', 'password', 'Fajariah Tri Lestari', 'Perempuan', 'no_hp', 'cirebon'],
['Yayat Hidayat', 'gmail.com', 'password', 'Yayat Hidayat', 'Laki-Laki', 'no_hp', 'cirebon'],
        ];
        foreach($users as $data) {
            $user = [
                'username' => $data[0],
                'email' => $data[0] ."@".$data[1],
                'password' => $data[2],
                'nama_user' => $data[3],
                'jk' => $data[4],
                'no_hp' => $data[5],
                'alamat' => $data[6]
            ];

            Users::create($user);
        }

        $wisatas = [
            ['Sunan Gunung Jati', 'Religi', 'Cirebon', 'Jl. Alun-Alun Ciledug No.53, Astana, Kec. Gunungjati, Kabupaten Cirebon, Jawa Barat 45151', 'gambar', 'lorem', 'kontak', '-6.671130', '108.540173'],
['Syekh Magelung Sakti', 'Religi', 'Cirebon', 'Karangkendal, Kec. Kapetakan, Kabupaten Cirebon, Jawa Barat 45152', 'gambar', 'lorem', 'kontak', '-6.578521', '108.504377'],
['Plangon', 'Religi', 'Cirebon', 'Jl.Pangeran Cakrabuana, Kelurahan Sendang, Kecamatan Sumber, Kabupaten Cirebon', 'gambar', 'lorem', 'kontak', '-6.774635', '108.48557'],
['Mbah Kuwu Sangkan', 'Religi', 'Cirebon', 'Jl. Lembah Cimandung, Kerandon, Kec. Talun, Kabupaten Cirebon, Jawa Barat 45171', 'gambar', 'lorem', 'kontak', '-6.778244', '108.498138'],
['Buyut Trusmi', 'Religi', 'Cirebon', 'Blok desa, Trusmi Wetan, Kec. Plered, Kabupaten Cirebon, Jawa Barat 45154', 'gambar', 'lorem', 'kontak', '-6.700197', '108.513502'],
['Nyimas Gandasari', 'Religi', 'Cirebon', 'Panguragan Lor, Kec. Panguragan, Kabupaten Cirebon, Jawa Barat 45163', 'gambar', 'lorem', 'kontak', '-6.623108', '108.453272'],
['Petilasan Sunan Bonang', 'Religi', 'Cirebon', 'Cupang, Kec. Gempol, Kabupaten Cirebon, Jawa Barat 45161', 'gambar', 'lorem', 'kontak', '-6.729461 ', '108.37858'],
['Batik Trusmi', 'Belanja', 'Cirebon', 'Jl. Syekh Datul Kahfi, Weru Kidul, Kec. Weru, Kabupaten Cirebon, Jawa Barat 45154', 'gambar', 'lorem', 'kontak', '-6.701205', '108.507793'],
['Mangrove Caplok Barong Ambulu', 'Edukasi', 'Cirebon', 'Jl. KH. Moh Yahya, Dusun Manis, Ambulu, Kec. Losari, Kabupaten Cirebon, Jawa Barat 45192', 'gambar', 'lorem', 'kontak', '-6.807875', '108.804541'],
['Gerabah Sitiwinangun', 'Edukasi', 'Cirebon', 'Jl. Bakung-Jamblang No.16, Jamblang, Kec. Jamblang, Kabupaten Cirebon, Jawa Barat 45156', 'gambar', 'lorem', 'kontak', '-6.699892', '108.456253'],
['Siwalk Setu Patok', 'Rekreasi', 'Cirebon', 'Setupatok, Kec. Mundu, Kabupaten Cirebon, Jawa Barat', 'gambar', 'lorem', 'kontak', '-6.780527', '108.568222'],
['Batu Lawang', 'Rekreasi', 'Cirebon', 'Cupang, Kec. Gempol, Kabupaten Cirebon, Jawa Barat 45161', 'gambar', 'lorem', 'kontak', '-6.727656', '108.380745'],
['Waterboom Splash Jungle Apita', 'Rekreasi', 'Cirebon', 'Jl. Tuparev No.46, Sutawinangun, Kec. Kedawung, Kabupaten Cirebon, Jawa Barat 45153', 'gambar', 'lorem', 'kontak', '-6.712421', '108.535658'],
['Kolam Renang Kiki', 'Rekreasi', 'Cirebon', 'Babakan, Kec. Sumber, Kabupaten Cirebon, Jawa Barat 45611', 'gambar', 'lorem', 'kontak', '-6.766143', '108.480481'],
['Waterpark Kyai Masni', 'Rekreasi', 'Cirebon', 'Perumahan Taman Kota, Ciperna, Talun, Cirebon, West Java 45171', 'gambar', 'lorem', 'kontak', '-6.765774', '108.532677'],
['Kolam Renang The Garden', 'Rekreasi', 'Cirebon', 'Jl. Pangeran Cakrabuana, Kecomberan, Kec. Talun, Kabupaten Cirebon, Jawa Barat 45171', 'gambar', 'lorem', 'kontak', '-6.752527', '108.525695'],
['Kolam Renang Segar Sejati', 'Rekreasi', 'Cirebon', 'Jl. Telagaremis Blok Tiga, Cikalahang, Kec. Dukupuntang, Kabupaten Cirebon, Jawa Barat 45652', 'gambar', 'lorem', 'kontak', '-6.780044', '108.419710'],
['Kolam Renang Hegar', 'Rekreasi', 'Cirebon', 'Jalan, Kelurahan No.07, Cikalahang, Kec. Dukupuntang, Kabupaten Cirebon, Jawa Barat 45652', 'gambar', 'lorem', 'kontak', '-6.784244', '108.404760'],
['Kolam Renang Simpatik', 'Rekreasi', 'Cirebon', 'Jl. Telaga Remis, Cikalahang, Kec. Dukupuntang, Kabupaten Cirebon, Jawa Barat 45652', 'gambar', 'lorem', 'kontak', '-6.781389', '108.418786'],
['Kolam Renang Banyu Panas', 'Rekreasi', 'Cirebon', 'Raya Cirebon-Paliman, Palimanan Bar., Kec. Palimanan, Kabupaten Cirebon, Jawa Barat 45161', 'gambar', 'lorem', 'kontak', '-6.712671', '108.399209'],
['Kolam Renang Seribu Wajan', 'Rekreasi', 'Cirebon', 'Bl. Lima, Panguragan Wetan, Kec. Panguragan, Kabupaten Cirebon, Jawa Barat 45163', 'gambar', 'lorem', 'kontak', '-6.627540', '108.464770'],
['Kolam Renang Tirta Mas Gemilang', 'Rekreasi', 'Cirebon', 'Jl. Raya Pantura Cirebon, Kebonturi, Kec. Arjawinangun, Kabupaten Cirebon, Jawa Barat 45162', 'gambar', 'lorem', 'kontak', '-6.651201', '108.407688'],
['Kolam Renang Zam Zam', 'Rekreasi', 'Cirebon', 'Jl. Palimanan - Sumber, Semplo, Kec. Palimanan, Kabupaten Cirebon, Jawa Barat 45161', 'gambar', 'lorem', 'kontak', '-6.717340', '108.435668'],
['Kolam Renang Jempol Waterboom', 'Rekreasi', 'Cirebon', 'Jl. Tol Kanci - Pejagan No.Km.233, Ciledug Lor, Kec. Ciledug, Kabupaten Cirebon, Jawa Barat 45188', 'gambar', 'lorem', 'kontak', '-6.894480', '108.750340'],
                    ];
        foreach($wisatas as $data) {
            $wisata = [
                'nama_wisata' => $data[0],
                'jenis_wisata' => $data[1],
                'kota' => $data[2],
                'alamat' => $data[3],
                'gambar_wisata' => $data[4],
                'deskripsi' => $data[5],
                'kontak' => $data[6],
                'lat'=> $data[7],
                'lng'=> $data[8],
            ];

            Wisata::create($wisata);
        }
        
        $rating = [
            ['Bilqis Nabila', '1', '4'],
['Burhanudin Bram', '1', '4'],
['Fajariah Tri Lestari', '1', '2'],
['Kang Umun', '1', '5'],
['Moelyadi Baleela', '1', '5'],
['Moms Aryan', '1', '4'],
['Suenti Een', '1', '3'],
['AF Ashari', '2', '4'],
['Burhanudin Bram', '2', '5'],
['Moelyadi Baleela', '2', '5'],
['AF Ashari', '3', '3'],
['Aidil Fitrah', '3', '5'],
['Ang Yon', '3', '5'],
['Jefry Anthony', '3', '5'],
['Kunto Dwi', '3', '4'],
['Monica Candra Dewi', '3', '3'],
['Suenti Een', '3', '5'],
['Za Irawan', '3', '5'],
['Ahmad Fadlu', '4', '4'],
['Khosiah Osi', '4', '3'],
['Moelyadi Baleela', '4', '5'],
['Nuraeni Indah Sari', '4', '5'],
['Prana Kunji', '4', '4'],
['Wahid Paruza', '4', '4'],
['Ang Yon', '5', '4'],
['Bilqis Nabila', '5', '3'],
['Jefry Anthony', '5', '5'],
['Moms Aryan', '5', '5'],
['Prana Kunji', '5', '5'],
['AF Ashari', '6', '4'],
['Ahmad Fadlu', '6', '4'],
['Burhanudin Bram', '6', '5'],
['Abdurakhman Wahid', '8', '4'],
['Ali Umar', '8', '4'],
['Ang Yon', '8', '5'],
['Bang Nizar', '8', '4'],
['Farhan Septian', '8', '3'],
['Hermawan Fawwaz', '8', '5'],
['Hesty Kartikasari', '8', '5'],
['Idemen', '8', '4'],
['Jaojatun Marup', '8', '4'],
['Jefry Anthony', '8', '5'],
['Kang Umun', '8', '5'],
['Kunto Dwi', '8', '2'],
['Mardi Yanto', '8', '5'],
['Mohammad Ridwan', '8', '5'],
['Monica Candra Dewi', '8', '4'],
['Nani Amani', '8', '5'],
['Nuraeni Indah Sari', '8', '5'],
['RBS 09', '8', '5'],
['Tani Wijaya', '8', '4'],
['Turadi', '8', '5'],
['Wahid Paruza', '8', '4'],
['Waviq Azizah', '8', '4'],
['Za Irawan', '8', '5'],
['Abdurakhman Wahid', '9', '5'],
['Fatimah Pamungkas', '9', '4'],
['Hardi Tabuti', '9', '5'],
['RBS 09', '9', '5'],
['Jaojatun Marup', '10', '4'],
['Kang Umun', '10', '5'],
['Mohammad Ridwan', '10', '5'],
['Sys', '10', '5'],
['Yuni Suman', '10', '5'],
['Hardi Tabuti', '11', '4'],
['RBS 09', '11', '5'],
['Za Irawan', '11', '5'],
['Hesty Kartikasari', '12', '5'],
['Kunto Dwi', '12', '5'],
['Mohammad Ridwan', '12', '5'],
['Moms Aryan', '12', '5'],
['Prana Kunji', '12', '5'],
['Risna Lijaman', '12', '5'],
['Suenti Een', '12', '5'],
['Sys', '12', '5'],
['Tunass Rieziek', '12', '4'],
['Za Irawan', '12', '5'],
['Abank', '13', '5'],
['Ali Umar', '13', '3'],
['Bang Nizar', '13', '4'],
['Farhan Septian', '13', '5'],
['Fatimah Pamungkas', '13', '5'],
['Hermawan Fawwaz', '13', '4'],
['Hesty Kartikasari', '13', '4'],
['Kunto Dwi', '13', '4'],
['Mohammad Ridwan', '13', '5'],
['Moms Aryan', '13', '5'],
['Monica Candra Dewi', '13', '3'],
['RBS 09', '13', '5'],
['Sutara', '13', '5'],
['Sys', '13', '5'],
['Waviq Azizah', '13', '4'],
['Yadi Suripto', '13', '4'],
['Abank', '14', '3'],
['Aidil Fitrah', '14', '5'],
['Ali Umar', '14', '3'],
['Bang Nizar', '14', '5'],
['Dena Febrian', '14', '3'],
['Fatimah Pamungkas', '14', '4'],
['Hermawan Fawwaz', '14', '3'],
['Hesty Kartikasari', '14', '3'],
['Jaojatun Marup', '14', '4'],
['Monica Candra Dewi', '14', '3'],
['Nur Soleh', '14', '3'],
['Tani Wijaya', '14', '5'],
['Waviq Azizah', '14', '3'],
['Abank', '15', '5'],
['Ahmad Fadlu', '15', '5'],
['Alexa Crb', '15', '5'],
['Ang Yon', '15', '3'],
['Hanifah', '15', '5'],
['Mardi Yanto', '15', '5'],
['Sutara', '15', '5'],
['Tunass Rieziek', '15', '5'],
['Yadi Suripto', '15', '3'],
['Abank', '16', '3'],
['Alexa Crb', '16', '5'],
['Hesty Kartikasari', '16', '4'],
['Jefry Anthony', '16', '5'],
['Nani Amani', '16', '5'],
['Nur Soleh', '16', '4'],
['Sutara', '16', '5'],
['Dena Febrian', '17', '3'],
['Farhan Septian', '17', '3'],
['Idemen', '17', '4'],
['Kang Umun', '17', '5'],
['Risna Lijaman', '17', '4'],
['Turadi', '17', '3'],
['Wahid Paruza', '17', '4'],
['Waviq Azizah', '17', '1'],
['Aidil Fitrah', '18', '5'],
['Ali Umar', '18', '5'],
['Bang Nizar', '18', '5'],
['Dena Febrian', '18', '4'],
['Fajariah Tri Lestari', '18', '2'],
['Fatimah Pamungkas', '18', '4'],
['Hanifah', '18', '4'],
['Hermawan Fawwaz', '18', '4'],
['Hesty Kartikasari', '18', '3'],
['Idemen', '18', '4'],
['Kang Umun', '18', '5'],
['Khosiah Osi', '18', '2'],
['Monica Candra Dewi', '18', '3'],
['Nani Amani', '18', '5'],
['Nur Soleh', '18', '4'],
['Nuraeni Indah Sari', '18', '4'],
['Tani Wijaya', '18', '5'],
['Waviq Azizah', '18', '4'],
['Yayat Hidayat', '18', '4'],
['Ali Umar', '19', '3'],
['Risna Lijaman', '19', '4'],
['Tani Wijaya', '19', '3'],
['AF Ashari', '20', '4'],
['Idemen', '20', '4'],
['Kunto Dwi', '20', '4'],
['Tunass Rieziek', '20', '5'],
['Yuni Suman', '20', '4'],
['Khosiah Osi', '21', '3'],
['Ali Umar', '22', '2'],
['Fajariah Tri Lestari', '22', '1'],
['Jefry Anthony', '22', '4'],
['Mardi Yanto', '22', '5'],
['Moms Aryan', '22', '5'],
['Nuraeni Indah Sari', '22', '5'],
['Turadi', '22', '5'],
['Waviq Azizah', '22', '3'],
['Yayat Hidayat', '22', '3'],
['Abdurakhman Wahid', '23', '5'],
['Alexa Crb', '23', '5'],
['Bilqis Nabila', '23', '3'],
['Khosiah Osi', '23', '3'],
['Waviq Azizah', '23', '1'],
['Yayat Hidayat', '23', '4'],
['Yuni Suman', '23', '4'],
['Fatimah Pamungkas', '24', '3'],
['Hanifah', '24', '5'],
['Hardi Tabuti', '24', '5'],
['Khosiah Osi', '24', '3'],
['Nani Amani', '24', '5'],
['Yadi Suripto', '24', '4'],

        ];
        foreach($rating as $data) {
            $rate = [
                'id_rating'=> uniqid(),
                'username' => $data[0],
                'id_wisata' => $data[1],
                'angka_rating' => $data[2],
            ];

            Rating::create($rate);
        }
    }
}
